name: Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: fetch-depth: 0

      - name: Show Python version
        run: python -V

      - name: Show API URL (simulated)
        run: echo "${{ github.api_url }}/repos/${{ github.repository }}"

      - name: Install dependencies
        run: |
          git config --global --add safe.directory '*'
          sudo apt-get update && sudo apt-get install -y git
          python3 -m pip install ham==0.0.5 --index-url https://pip:glpat-aq2VpazxthkoqZ9b3bDz@git.rys.one/api/v4/groups/phd/-/packages/pypi/simple
          python3 -m pip install worst==0.0.5 --index-url https://pip:glpat-aq2VpazxthkoqZ9b3bDz@git.rys.one/api/v4/groups/phd/-/packages/pypi/simple
          python3 -m pip install ninit --index-url https://pip:glpat-aq2VpazxthkoqZ9b3bDz@git.rys.one/api/v4/groups/phd/-/packages/pypi/simple

      - name: Run ninit command
        run: |
          ninit --host notifier.rys.app --port 443 --protocol wss --repository .
