name: Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git safe directory
        run: |
          git config --global --add safe.directory '*'

      - name: Cache Python venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Set up Python virtual environment
        shell: bash
        run: |
          if [ ! -d ".venv" ]; then
            python3 -m venv .venv
            . .venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt --index-url https://pip:glpat-aq2VpazxthkoqZ9b3bDz@git.rys.one/api/v4/groups/phd/-/packages/pypi/simple
          else
            echo "Using cached virtual environment"
          fi

      - name: Activate venv and run ninit
        shell: bash
        run: |
          . .venv/bin/activate
          ninit --host notifier.rys.app --port 443 --protocol wss --repository .
